name: background_location_example
description: Demonstrates how to use the background_location plugin.
publish_to: "none"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  background_location:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
