name: background_location_2
description: A Flutter plugin to get location updates in the background for both
  Android and iOS. Uses CoreLocation for iOS and FusedLocationProvider for
  Android. Based on the background_location library by almoullim
version: 0.16.0
homepage: https://github.com/BWMuller/background_location
repository: https://github.com/BWMuller/background_location

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.almoullim.background_location
        pluginClass: BackgroundLocationPlugin
      ios:
        pluginClass: BackgroundLocationPlugin
