name: background_location
description: A Flutter plugin to get location updates in the background for both Android and iOS. Uses CoreLocation for iOS and FusedLocationProvider for Android.
version: 0.4.1
homepage: https://github.com/Almoullim/background_location
repository: https://github.com/Almoullim/background_location

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^6.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.almoullim.background_location
        pluginClass: BackgroundLocationPlugin
      ios:
        pluginClass: BackgroundLocationPlugin
