name: background_location
description: A Flutter plugin to get location updates in the background for both
  Android and iOS. Uses CoreLocation for iOS and FusedLocationProvider for
  Android.
version: 0.9.0
homepage: https://github.com/Almoullim/background_location
repository: https://github.com/Almoullim/background_location

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #test: ^1.16.8
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.almoullim.background_location
        pluginClass: BackgroundLocationPlugin
      ios:
        pluginClass: BackgroundLocationPlugin
